<?php

namespace Bricks\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrickLicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrickLicenseRepository extends EntityRepository
{
}
